---

- hosts: all
  become: true
  tasks:
  

  - name: update repo
    yum:
      update_cache: yes

  - name: install apache2 package
    yum:
      name: httpd
      state: absent

  - name: add php support
    yum:
      name: php
      state: absent
