---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Centos) 
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create Simone user
    tags: always
    user: 
      name: Simone
      group: root 

  - name: add ssh key for Simone
    tags: always
    authorized_key:
      user: Simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH5aIE3sXssFGNwuv8bcFw3tq6hqgWyQW5sqqI21LSIW “andrei”"

  - name: add sudoer file for Simone
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440  
        
- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php for Ubuntu
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for Centos
      tags: apache,amazon,httpd
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "Amazon"  

    - name: start httpd (Centos)
      tags: amazon,apache,httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Amazon"

    - name: change email address for admin
      tags: apache,amazon,httpd
      lineinfile: 
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@some.com
      when: ansible_distribution == "Amazon"
      register: httpdstare

    - name: restart httpd
      tags: apache,amazon,https
      service:
        name: httpd
        state: restarted
      when: httpdstare.changed

        
    - name: copy default html files
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb (Centos)
    tags: amazon,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon"

  - name:
    tags: mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
