---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Centos) 
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php for Ubuntu
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for Centos
      tags: apache,amazon,httpd
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "Amazon"  

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb (Centos)
    tags: amazon,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon"

  - name:
    tags: mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
